name: Hex Calculator CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults: # Set default working directory for all steps
      run:
        working-directory: ./hex_calculator
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watchAll=false

      - name: Run GUI Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
