name: Hex Calculator CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install
        working-directory: ./hex_calculator

      - name: Run unit tests
        run: npm test -- --watchAll=false
        working-directory: ./hex_calculator

      - name: Run Cypress GUI tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          working-directory: ./hex_calculator
          install-command: npm install
